version: '3.9'

services:

  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_DATABASE}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django-app:
    build:
      context: ./main_dir
      dockerfile: Dockerfile
    volumes:
      - ./main_dir/:/usr/src/main_dir/
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  redis:
    container_name: redis
    image: redis:7-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_db:/usr/local/etc/redis

  celery-worker:
    build:
      context: ./main_dir
      dockerfile: Dockerfile.service
    volumes:
      - ./main_dir/:/usr/src/main_dir/
    env_file:
      - .env
    command: celery -A config worker --loglevel=info
    links:
      - redis
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: ./main_dir
      dockerfile: Dockerfile.service
    volumes:
      - ./main_dir/:/usr/src/main_dir/
    env_file:
      - .env
    command: celery -A config beat -l info -S django --loglevel=info
    depends_on:
      - db
      - redis

volumes:
  postgres_db:
  redis_db:
